#!/usr/bin/env node
// Builds a standalone desktop executable. Two ways, because they trade off
// very differently:
//
//   --native        366 kB. A C launcher (tools/launcher.c) with the game
//                   embedded, handed to the default browser. Windows only,
//                   needs mingw-w64 to build. This is the default.
//   (no flag)       ~83 MB. Node's single-executable format: the official Node
//                   binary with the game injected as a resource, served over a
//                   loopback port. Cross-builds to macOS and Linux too.
//
// The size gap is the whole point: the game is 326 kB, so the SEA build spends
// 99.6% of its weight on a JavaScript runtime whose only job is to serve one
// static file. Keep the SEA path for the platforms mingw cannot target.
//
//   node tools/build-exe.js --native             -> dist/BuildAHooper.exe
//   node tools/build-exe.js                      -> dist/BuildAHooper.exe (SEA)
//   node tools/build-exe.js --target linux-x64   (or darwin-arm64, darwin-x64…)
//   node tools/build-exe.js --target host        -> build for this machine
//
// Cross-building the SEA works because the "compiler" is just the official Node
// binary for the target platform with a blob appended, so the only thing that
// has to run locally is postject.
//
// The result is UNSIGNED. Windows SmartScreen will warn on first run, and
// macOS Gatekeeper will refuse a downloaded build outright. Code signing needs
// a certificate this build cannot have.

import { execFileSync } from 'node:child_process';
import { createWriteStream } from 'node:fs';
import { chmod, mkdir, copyFile, writeFile, stat, access } from 'node:fs/promises';
import { Readable } from 'node:stream';
import { pipeline } from 'node:stream/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(fileURLToPath(new URL('.', import.meta.url)), '..');
const NODE_VERSION = process.version; // build against the runtime we tested on
const argv = process.argv.slice(2);
const flag = (name, fb) => {
  const i = argv.indexOf(name);
  return i >= 0 ? argv[i + 1] : fb;
};

const TARGETS = {
  'win-x64': { file: 'node.exe', out: 'BuildAHooper.exe', dir: 'win-x64' },
  'linux-x64': { file: 'node', out: 'build-a-hooper', dir: 'linux-x64' },
  'darwin-x64': { file: 'node', out: 'BuildAHooper-mac-x64', dir: 'darwin-x64' },
  'darwin-arm64': { file: 'node', out: 'BuildAHooper-mac-arm64', dir: 'darwin-arm64' },
};

let targetName = flag('--target', 'win-x64');
if (targetName === 'host') {
  targetName = `${process.platform === 'win32' ? 'win' : process.platform}-${process.arch}`;
}
const target = TARGETS[targetName];
if (!target) {
  console.error(`unknown target "${targetName}" — one of: ${Object.keys(TARGETS).join(', ')}, host`);
  process.exit(1);
}

const CACHE = join(ROOT, '.cache');
const DIST = join(ROOT, 'dist');
await mkdir(CACHE, { recursive: true });
await mkdir(DIST, { recursive: true });

const exists = (p) => access(p).then(() => true, () => false);
const run = (cmd, args) => execFileSync(cmd, args, { cwd: ROOT, stdio: 'inherit' });

// 1. The game itself, as one HTML file.
console.log('· bundling the game');
run(process.execPath, ['tools/bundle.js']);

// ---------------------------------------------------------------------------
// --native: a small Windows launcher instead of a bundled runtime.
//
// The SEA build below is ~83 MB, of which the game is 326 kB — the rest is a
// whole JavaScript runtime whose only job is to serve one static file. This
// path compiles a C launcher that embeds the HTML and hands it to the default
// browser, for ~0.5% of the size and no server or port. Same game.
// ---------------------------------------------------------------------------
if (argv.includes('--native')) {
  const CC = 'x86_64-w64-mingw32-gcc';
  try {
    execFileSync('which', [CC], { stdio: 'ignore' });
  } catch {
    console.error(`\n  ${CC} not found — install mingw-w64, or drop --native for the SEA build.`);
    process.exit(1);
  }

  const { readFile: rf, writeFile: wf } = await import('node:fs/promises');
  const html = await rf(join(DIST, 'build-a-hooper.html'));

  // Emit the page as a C byte array. Not a string literal: MSVC-era limits and
  // escaping rules make a 326 kB literal a bad idea, and a plain array has none
  // of those problems.
  const lines = [];
  for (let i = 0; i < html.length; i += 20) {
    lines.push('  ' + [...html.subarray(i, i + 20)].map((b) => b).join(',') + ',');
  }
  await wf(
    join(CACHE, 'game_data.h'),
    `/* Generated by tools/build-exe.js --native. Do not edit. */\n` +
      `static const unsigned char GAME_HTML[] = {\n${lines.join('\n')}\n};\n` +
      `#define GAME_HTML_LEN ${html.length}\n`,
  );

  const outPath = join(DIST, 'BuildAHooper.exe');
  console.log('· compiling the launcher');
  run(CC, [
    join(ROOT, 'tools', 'launcher.c'),
    '-I', CACHE,
    '-o', outPath,
    '-O2', '-s',
    '-mwindows', // GUI subsystem: no console window flashes up
    '-lshell32',
  ]);

  const { size } = await stat(outPath);
  console.log(`\n  dist/BuildAHooper.exe — ${(size / 1024).toFixed(0)} kB (win-x64, native launcher)`);
  console.log('  Unsigned: SmartScreen will warn on first run.');
  process.exit(0);
}

// 2. The target platform's Node runtime.
// Named `runtime-` rather than `node-` so it cannot collide with the
// `node-<ver>-<target>` directory the tarball extracts to.
const runtime = join(CACHE, `runtime-${NODE_VERSION}-${targetName}${targetName.startsWith('win') ? '.exe' : ''}`);
if (await exists(runtime)) {
  console.log(`· runtime cached (${NODE_VERSION} ${targetName})`);
} else {
  // Windows ships a bare node.exe; the others only come inside a tarball, so
  // for those we fetch the archive and pull the one file out of it.
  console.log(`· downloading node ${NODE_VERSION} for ${targetName}`);
  if (targetName.startsWith('win')) {
    const url = `https://nodejs.org/dist/${NODE_VERSION}/${target.dir}/node.exe`;
    const res = await fetch(url);
    if (!res.ok) throw new Error(`${url} -> ${res.status}`);
    await pipeline(Readable.fromWeb(res.body), createWriteStream(runtime));
  } else {
    const base = `node-${NODE_VERSION}-${target.dir}`;
    const url = `https://nodejs.org/dist/${NODE_VERSION}/${base}.tar.gz`;
    const res = await fetch(url);
    if (!res.ok) throw new Error(`${url} -> ${res.status}`);
    const tgz = join(CACHE, `${base}.tar.gz`);
    await pipeline(Readable.fromWeb(res.body), createWriteStream(tgz));
    run('tar', ['-xzf', tgz, '-C', CACHE, `${base}/bin/node`]);
    await copyFile(join(CACHE, base, 'bin', 'node'), runtime);
  }
  await chmod(runtime, 0o755);
}

// 3. The SEA blob: entry script plus the game as a named asset.
console.log('· building the SEA blob');
const seaConfig = join(CACHE, 'sea-config.json');
await writeFile(
  seaConfig,
  JSON.stringify(
    {
      main: 'tools/exe-entry.cjs',
      output: join(CACHE, 'sea-prep.blob'),
      disableExperimentalSEAWarning: true,
      assets: { 'game.html': 'dist/build-a-hooper.html' },
    },
    null,
    2,
  ),
);
run(process.execPath, ['--experimental-sea-config', seaConfig]);

// The official node.exe is Authenticode-signed, and appending a resource
// invalidates that signature. Node's docs say to remove it with `signtool
// remove`, which does not exist off Windows — so strip the certificate table
// directly. Leaving a *corrupt* signature is worse than shipping none: Windows
// reports it as tampered rather than merely unknown.
async function stripAuthenticode(file) {
  const { readFile: rf, writeFile: wf } = await import('node:fs/promises');
  const buf = await rf(file);
  const peOff = buf.readUInt32LE(0x3c);
  if (buf.toString('ascii', peOff, peOff + 4) !== 'PE\0\0') return false;

  const optOff = peOff + 24;
  const magic = buf.readUInt16LE(optOff);
  // Data directories sit after the optional header: 112 bytes in for PE32+,
  // 96 for PE32.
  const dirOff = optOff + (magic === 0x20b ? 112 : 96);
  const certOff = dirOff + 4 * 8; // directory entry 4 = Certificate Table
  const certAddr = buf.readUInt32LE(certOff);
  const certSize = buf.readUInt32LE(certOff + 4);
  if (!certAddr || !certSize) return false;

  buf.writeUInt32LE(0, certOff);
  buf.writeUInt32LE(0, certOff + 4);
  buf.writeUInt32LE(0, optOff + 64); // checksum, now meaningless
  // Unlike every other directory, the certificate table is addressed by file
  // offset and always trails the image, so dropping it is a truncation.
  await wf(file, buf.subarray(0, certAddr));
  return true;
}

// 4. Inject it into a copy of the runtime.
const outPath = join(DIST, target.out);
await copyFile(runtime, outPath);
if (targetName.startsWith('win')) {
  const stripped = await stripAuthenticode(outPath);
  console.log(stripped ? '· stripped the now-invalid Authenticode signature' : '· no signature to strip');
}
console.log('· injecting');
const postject = [
  'postject',
  outPath,
  'NODE_SEA_BLOB',
  join(CACHE, 'sea-prep.blob'),
  '--sentinel-fuse',
  'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
];
// macOS binaries need the blob in a named segment; PE and ELF do not.
if (targetName.startsWith('darwin')) postject.push('--macho-segment-name', 'NODE_SEA');
run('npx', ['--yes', ...postject]);
if (!targetName.startsWith('win')) await chmod(outPath, 0o755);

const { size } = await stat(outPath);
console.log(`\n  dist/${target.out} — ${(size / 1024 / 1024).toFixed(0)} MB (${targetName})`);
console.log('  Unsigned: Windows SmartScreen will warn on first run.');
