#!/usr/bin/env node
// Builds docs/ — an installable, offline-capable web app ready for GitHub Pages.
//
//   node tools/build-site.js
//
// Output is deliberately tiny: one HTML file with everything inlined, a
// manifest, a service worker, and the icon set. No build pipeline, no hosting
// bill, and nothing to review — it installs to a phone home screen straight
// from the URL.

import { execFileSync } from 'node:child_process';
import { readFile, writeFile, mkdir, rm } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(fileURLToPath(new URL('.', import.meta.url)), '..');
const DOCS = join(ROOT, 'docs');
const TMP = join(ROOT, '.cache', 'site-body.html');

const NAME = 'Build a Hooper';
const SHORT = 'Hooper';
const DESC =
  'Roll a basketball player one attribute at a time, scored against what is expected for his height, then simulate the career it was worth.';
const THEME = '#150f0b';
const ACCENT = '#ffa92b';

await rm(DOCS, { recursive: true, force: true });
await mkdir(DOCS, { recursive: true });

// 1. The game, as one self-contained body fragment.
execFileSync(process.execPath, ['tools/bundle.js', '--fragment', '-o', TMP], {
  cwd: ROOT,
  stdio: 'inherit',
});
const body = await readFile(TMP, 'utf8');

// 2. Icons.
execFileSync(process.execPath, ['tools/make-icons.js', join(DOCS, 'icons')], {
  cwd: ROOT,
  stdio: 'inherit',
});

// 3. The page, with everything an install prompt needs.
const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
<title>${NAME}</title>
<meta name="description" content="${DESC}" />
<meta name="theme-color" content="${THEME}" />
<link rel="manifest" href="manifest.webmanifest" />
<link rel="icon" href="icons/favicon-32.png" sizes="32x32" />
<link rel="apple-touch-icon" href="icons/apple-touch-icon.png" />
<!-- iOS still needs these; it does not read the manifest for standalone mode. -->
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
<meta name="apple-mobile-web-app-title" content="${SHORT}" />
<meta name="mobile-web-app-capable" content="yes" />
<meta property="og:title" content="${NAME}" />
<meta property="og:description" content="${DESC}" />
<meta property="og:type" content="website" />
</head>
<body>
${body}
<script>
  // Registered after load so it never competes with first paint.
  if ('serviceWorker' in navigator) {
    addEventListener('load', () => {
      navigator.serviceWorker.register('sw.js').catch(() => {});
    });
  }
</script>
</body>
</html>`;
await writeFile(join(DOCS, 'index.html'), html);

// 4. Manifest.
const manifest = {
  name: NAME,
  short_name: SHORT,
  description: DESC,
  start_url: '.',
  scope: '.',
  display: 'standalone',
  orientation: 'portrait',
  background_color: THEME,
  theme_color: THEME,
  categories: ['games', 'sports'],
  icons: [
    { src: 'icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
    { src: 'icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
    { src: 'icons/icon-192-maskable.png', sizes: '192x192', type: 'image/png', purpose: 'maskable' },
    { src: 'icons/icon-512-maskable.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
  ],
};
await writeFile(join(DOCS, 'manifest.webmanifest'), JSON.stringify(manifest, null, 2));

// 5. Service worker. The cache name carries a hash of the page, so shipping a
//    new build invalidates the old one instead of leaving people on a stale
//    copy forever — the classic way a PWA appears not to update.
const version = createHash('sha256').update(html).digest('hex').slice(0, 12);
const sw = `// Generated by tools/build-site.js — do not edit.
const CACHE = 'hooper-${version}';
const ASSETS = [
  './',
  'index.html',
  'manifest.webmanifest',
  'icons/icon-192.png',
  'icons/icon-512.png',
  'icons/icon-192-maskable.png',
  'icons/icon-512-maskable.png',
  'icons/apple-touch-icon.png',
  'icons/favicon-32.png',
];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return;
  // Navigations go to the network first so a new build lands as soon as there
  // is a connection, and fall back to cache so the app still opens offline.
  if (e.request.mode === 'navigate') {
    e.respondWith(
      fetch(e.request)
        .then((r) => {
          const copy = r.clone();
          caches.open(CACHE).then((c) => c.put('index.html', copy));
          return r;
        })
        .catch(() => caches.match('index.html')),
    );
    return;
  }
  e.respondWith(caches.match(e.request).then((hit) => hit || fetch(e.request)));
});
`;
await writeFile(join(DOCS, 'sw.js'), sw);

// GitHub Pages runs Jekyll by default, which silently drops files and folders
// beginning with an underscore. Nothing here starts with one today, but this
// costs nothing and removes a whole category of "works locally, 404 on Pages".
await writeFile(join(DOCS, '.nojekyll'), '');

const size = Buffer.byteLength(html) / 1024;
console.log(`\n  docs/ — installable web app, index.html ${size.toFixed(0)} kB, cache ${version}`);
