#!/usr/bin/env node
// Downloads the three display faces and writes web/fonts.css with each one
// inlined as a base64 data URI.
//
// This is a build step, not a runtime dependency: the published page runs under
// a CSP that blocks external hosts, so a <link> to a font CDN would silently
// fall back to system sans and quietly lose the whole typographic identity.
// Run it only when the font list changes; the generated CSS is committed.
//
//   node tools/fetch-fonts.js
//
// Anton, Archivo and JetBrains Mono are all SIL Open Font License 1.1, which
// permits embedding. See web/fonts.css for the retained notice.

import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(fileURLToPath(new URL('.', import.meta.url)), '..');
const API =
  'https://fonts.googleapis.com/css2?family=Anton&family=Archivo:wght@400;600;700&family=JetBrains+Mono:wght@400;700&display=swap';
const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const css = await (await fetch(API, { headers: { 'User-Agent': UA } })).text();

// Split into @font-face blocks and keep only the plain-latin subset of each.
const blocks = css.split('@font-face').slice(1);
const wanted = [];
for (const b of blocks) {
  const family = b.match(/font-family:\s*'([^']+)'/)?.[1];
  const weight = b.match(/font-weight:\s*(\d+)/)?.[1];
  const url = b.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
  const range = b.match(/unicode-range:\s*([^;]+);/)?.[1] ?? '';
  // The latin subset starts at U+0000-00FF; latin-ext and the rest start higher.
  if (!family || !url || !range.startsWith('U+0000-00FF')) continue;
  wanted.push({ family, weight, url, range });
}

if (wanted.length !== 6) {
  console.error(`expected 6 latin faces, parsed ${wanted.length} — the API response shape changed`);
  process.exit(1);
}

const out = [
  '/* Generated by tools/fetch-fonts.js — do not edit by hand.',
  ' *',
  ' * Anton, Archivo and JetBrains Mono, SIL Open Font License 1.1.',
  ' * Copyright the Anton Project Authors, the Archivo Project Authors, and',
  ' * JetBrains s.r.o. Latin subsets only, inlined because the published page',
  ' * runs under a CSP that blocks font CDNs. */',
  '',
];

let bytes = 0;
for (const f of wanted) {
  const buf = Buffer.from(await (await fetch(f.url)).arrayBuffer());
  bytes += buf.length;
  out.push(
    '@font-face {',
    `  font-family: '${f.family}';`,
    '  font-style: normal;',
    `  font-weight: ${f.weight};`,
    '  font-display: swap;',
    `  src: url(data:font/woff2;base64,${buf.toString('base64')}) format('woff2');`,
    `  unicode-range: ${f.range};`,
    '}',
    '',
  );
}

await writeFile(join(ROOT, 'web/fonts.css'), out.join('\n'));
console.log(
  `web/fonts.css — ${wanted.length} faces, ${(bytes / 1024).toFixed(0)} kB of woff2 ` +
    `(${(out.join('\n').length / 1024).toFixed(0)} kB as base64)`,
);
