/* Hoop Life — native Windows launcher.
 *
 * The whole game is one self-contained HTML file. This writes it to the temp
 * directory and hands it to the default browser, which produces a ~400 kB
 * executable instead of the ~83 MB a bundled JavaScript runtime costs. The
 * game is identical either way; only the delivery differs.
 *
 * Built by tools/build-exe.js --native. The HTML arrives as game_data.h, a
 * generated byte array, so there is nothing to unpack at runtime and no server
 * or port involved.
 *
 * WinMain rather than main so Windows does not flash a console window.
 */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <shellapi.h>
#include <stdio.h>

#include "game_data.h"

int WINAPI WinMain(HINSTANCE inst, HINSTANCE prev, LPSTR args, int show) {
  (void)inst; (void)prev; (void)args; (void)show;

  char dir[MAX_PATH];
  DWORD n = GetTempPathA(MAX_PATH, dir);
  if (n == 0 || n > MAX_PATH) {
    MessageBoxA(NULL, "Could not locate a temporary directory.", "Hoop Life", MB_ICONERROR);
    return 1;
  }

  char path[MAX_PATH];
  if (snprintf(path, sizeof(path), "%sbuild-a-hooper.html", dir) >= (int)sizeof(path)) {
    MessageBoxA(NULL, "Temporary path too long.", "Hoop Life", MB_ICONERROR);
    return 1;
  }

  /* Rewrite every launch: an older copy left by a previous version would
     otherwise be served forever. */
  HANDLE f = CreateFileA(path, GENERIC_WRITE, FILE_SHARE_READ, NULL,
                         CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL);
  if (f == INVALID_HANDLE_VALUE) {
    MessageBoxA(NULL, "Could not write the game file.", "Hoop Life", MB_ICONERROR);
    return 1;
  }

  DWORD written = 0, total = 0;
  while (total < GAME_HTML_LEN) {
    if (!WriteFile(f, GAME_HTML + total, GAME_HTML_LEN - total, &written, NULL) || written == 0) {
      CloseHandle(f);
      MessageBoxA(NULL, "Could not write the game file.", "Hoop Life", MB_ICONERROR);
      return 1;
    }
    total += written;
  }
  CloseHandle(f);

  /* ShellExecute returns a value <= 32 on failure; the type is a legacy HINSTANCE. */
  HINSTANCE rc = ShellExecuteA(NULL, "open", path, NULL, NULL, SW_SHOWNORMAL);
  if ((INT_PTR)rc <= 32) {
    char msg[MAX_PATH + 128];
    snprintf(msg, sizeof(msg),
             "Could not open a browser automatically.\n\nOpen this file yourself:\n%s", path);
    MessageBoxA(NULL, msg, "Hoop Life", MB_ICONINFORMATION);
    return 1;
  }
  return 0;
}
